language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

env:
  global:
    - SONATYPE_USERNAME=80ymBYBJ
    - secure: "GY8Fd8wbtl7trlSymM3af0BTTj9lzdU/+2sKqD8/RdZBLlSv4BK+yG+u6YfQ\ndlqWdgMaed52QaJ9Q+z2Zl8d4wAUrOgplE+MSpAVOYmkeuY2hPdGeyOu691B\neKo3DocrR4OA7Rx60PcyyqrpDUBiJWtcpHQpQuSpCNQn+T07H6w="

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq rpm alien
 # Heirloom Packaging Tools provide pkgmk and pkginfo needed for sysv pkg integration tests
 - wget http://koji.spacewalkproject.org/packages/heirloom-pkgtools/1.070227/6.el6/x86_64/heirloom-pkgtools-1.070227-6.el6.x86_64.rpm
 - sudo alien heirloom-pkgtools-1.070227-6.el6.x86_64.rpm
 - sudo dpkg -i heirloom-pkgtools_1.070227-7_amd64.deb 
 - sudo chown -R ${USER} /var/sadm

install: "mvn install -DskipTests -U -B"

script: "mvn install -U -B -Pintegration-tests -Dinvoker.noLog=true"

after_success:
  - python .travis-addServer.py
  # No need to run clean or run tests when simply deploying.
  - mvn -DskipTests -B -Phandbook --settings ~/.m2/mySettings.xml deploy
